version: '3.8'

services: 
  db:
    image: mysql:8.0
    container_name: motodatalogger_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password # Replace with a strong password
      MYSQL_DATABASE: motodataloggerdb # Choose your database name
      MYSQL_USER: motodataloggeruser # Choose your username
      MYSQL_PASSWORD: your_mysql_user_password # Replace with a strong password
    ports:
      - "3306:3306"
    volumes:
      - motodatalogger_db_data:/var/lib/mysql
    networks:
      - motodatalogger_network

  api:
    build:
      context: .
      dockerfile: API/Dockerfile # Path to your API Dockerfile
    container_name: motodatalogger_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Or Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=motodataloggerdb;User=motodataloggeruser;Password=your_mysql_user_password # Connection string
      - Jwt__Key=super_secret_key_for_jwt_tokens_1234567890 # Add your JWT settings
      - Jwt__Issuer=MotoDataLoggerAPI
      - Jwt__Audience=MotoDataLoggerUsers
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - motodatalogger_network

volumes:
  motodatalogger_db_data:

networks:
  motodatalogger_network:
    driver: bridge
